/**
 * contact link approve 状态机。
 *
 * 关键点（中文）
 * - 远端 approve 只有一个入口：校验 link -> 保存 contact -> 消费 link。
 * - 同一个 agent 在 link 有效期内可重试，用于恢复“远端已保存、本地保存失败”的半建联。
 * - contact token 由协议自动交换，不依赖用户手动配置环境变量。
 */

import type { ContactApproveLinkResponse } from "@/types/contact/ContactLink.js";
import type { ApproveContactLinkRequestInput } from "@/types/contact/ContactApproval.js";
import {
  createStableContactId,
  normalizeContactEndpoint,
  saveContact,
} from "./ContactStore.js";
import {
  readContactLinkRecord,
  saveContactLinkRecord,
} from "./LinkStore.js";
import {
  createContactToken,
  hashContactToken,
} from "./Token.js";

export const CONTACT_LINK_NOT_FOUND_ERROR =
  "Contact link not found. This runtime does not have that link record. This usually means the approve request reached the wrong endpoint or port, the link was generated by another agent/project, or the local link store was cleared. If the code is expired, the remote agent returns Contact link expired instead.";

function failure(params: {
  ownerAgentName: string;
  endpoint: string;
  error: string;
}): ContactApproveLinkResponse {
  return {
    success: false,
    agentName: params.ownerAgentName,
    endpoint: params.endpoint,
    tokenForOwner: "",
    error: params.error,
  };
}

/**
 * 执行远端 link approve 状态转换。
 */
export async function approveContactLinkRequest(
  input: ApproveContactLinkRequestInput,
): Promise<ContactApproveLinkResponse> {
  const nowMs = input.nowMs ?? Date.now();
  const link = await readContactLinkRecord(input.projectRoot, input.request.linkId);
  if (!link) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: input.ownerEndpoint,
      error: CONTACT_LINK_NOT_FOUND_ERROR,
    });
  }
  if (link.expiresAt <= nowMs) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Contact link expired",
    });
  }
  if (hashContactToken(input.request.secret) !== link.secretHash) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Invalid contact link secret",
    });
  }
  if (link.usedAt) {
    if (
      link.approvedAgentName === input.request.agentName &&
      link.tokenForOwner
    ) {
      return {
        success: true,
        agentName: input.ownerAgentName,
        endpoint: link.endpoint,
        tokenForOwner: link.tokenForOwner,
      };
    }
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Contact link already used",
    });
  }

  const tokenForOwner = createContactToken();
  const requesterEndpoint = input.request.endpoint
    ? normalizeContactEndpoint(input.request.endpoint)
    : null;
  const tokenForRequester = requesterEndpoint
    ? String(input.request.tokenForRequester || "").trim()
    : null;
  if (requesterEndpoint && !tokenForRequester) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Contact approve request is missing the peer callback token",
    });
  }

  await saveContact(input.projectRoot, {
    id: createStableContactId(input.request.agentName),
    name: input.request.agentName,
    endpoint: requesterEndpoint,
    reachability: requesterEndpoint ? "bidirectional" : "inbound",
    status: "trusted",
    outboundToken: tokenForRequester,
    inboundTokenHash: hashContactToken(tokenForOwner),
    createdAt: nowMs,
    lastSeenAt: nowMs,
  });
  await saveContactLinkRecord(input.projectRoot, {
    ...link,
    usedAt: nowMs,
    approvedAgentName: input.request.agentName,
    approvedEndpoint: requesterEndpoint,
    tokenForOwner,
  });

  return {
    success: true,
    agentName: input.ownerAgentName,
    endpoint: link.endpoint,
    tokenForOwner,
  };
}
