packages:
  - products/console
  - homepage
  - packages/agent
  - packages/plugins
  - packages/city
  - packages/ui
  - products/chrome-extension
  - examples/*

onlyBuiltDependencies:
  - better-sqlite3
