packages:
  - products/console
  - homepage
  - packages/agent
  - packages/infra
  - packages/services
  - packages/conduit
  - packages/plugins
  - packages/city
  - packages/ui
  - products/chrome-extension
  - blocks/*
  - examples/*

onlyBuiltDependencies:
  - better-sqlite3
