packages:
  - products/console
  - homepage
  - packages/agent
  - packages/city
  - packages/services
  - packages/plugins
  - packages/type
  - cli/*
  - packages/ui
  - products/chrome-extension
  - cities/*
  - examples/*

onlyBuiltDependencies:
  - better-sqlite3
