name = "downcity"
main = "src/index.ts"
compatibility_date = "2025-05-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "downcity-db"
database_id = "4e3fc23e-29f2-430e-bcbb-4c4b9d941834"

[observability]
enabled = true
