/**
 * contact endpoint 用户提示。
 *
 * 关键点（中文）
 * - `contact link` / `contact approve` 会被 agent 自己调用，返回结果必须直接说明可达性限制。
 * - loopback/private endpoint 不是错误，但需要提醒用户不要拿给无法访问该地址的远端 agent。
 */

import type { ContactEndpointReachability } from "@/types/contact/ContactEndpoint.js";

function readHostname(endpoint: string): string {
  const value = String(endpoint || "").trim();
  if (!value) return "";
  try {
    return new URL(value).hostname.toLowerCase().replace(/^\[|\]$/g, "");
  } catch {
    return "";
  }
}

function isPrivateIpv4(hostname: string): boolean {
  const parts = hostname.split(".").map((item) => Number.parseInt(item, 10));
  if (parts.length !== 4 || parts.some((item) => Number.isNaN(item))) return false;
  if (parts[0] === 10) return true;
  if (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) return true;
  if (parts[0] === 192 && parts[1] === 168) return true;
  if (parts[0] === 169 && parts[1] === 254) return true;
  return false;
}

/**
 * 判断 endpoint 的粗粒度可达范围。
 */
export function classifyContactEndpoint(
  endpoint: string,
): ContactEndpointReachability {
  const hostname = readHostname(endpoint);
  if (!hostname) return "unknown";
  if (
    hostname === "localhost" ||
    hostname === "::1" ||
    hostname.startsWith("127.")
  ) {
    return "loopback";
  }
  if (isPrivateIpv4(hostname)) return "private";
  return "public";
}

/**
 * 生成 `contact link` 返回提示。
 */
export function buildContactLinkNotes(params: {
  /**
   * link code 内写入的 endpoint。
   */
  endpoint: string;
}): string[] {
  const reachability = classifyContactEndpoint(params.endpoint);
  if (reachability === "loopback") {
    return [
      "This link endpoint is local-only. Only an agent on the same machine can approve it; a server agent cannot approve a link generated by this local agent.",
      "Start city from a reachable environment before generating a new link; city start automatically writes the public host used by contact links when it can detect one.",
    ];
  }
  if (reachability === "private") {
    return [
      "This link endpoint is private-network only. Agents must be on the same LAN/VPN to approve it; a public server agent may not be able to reach it.",
    ];
  }
  if (reachability === "public") {
    return [
      "This link can be approved by agents that can reach this endpoint before the code expires.",
      "Downcity cannot verify firewall or NAT reachability from here; if approval cannot connect, restart city from a reachable server, domain, or tunnel.",
    ];
  }
  return [
    "Downcity could not classify this link endpoint. Make sure the receiving agent can reach it before approving.",
  ];
}

/**
 * 生成 `contact approve` 返回提示。
 */
export function buildContactApproveNotes(params: {
  /**
   * link code 中的目标 endpoint。
   */
  targetEndpoint: string;
  /**
   * approve 方随请求发送给对方的 endpoint。
   */
  requesterEndpoint?: string;
  /**
   * 对方是否已经主动 ping 回 approve 方并确认成功。
   */
  callbackConfirmed?: boolean;
}): string[] {
  const notes: string[] = [];
  const targetReachability = classifyContactEndpoint(params.targetEndpoint);
  if (targetReachability === "loopback") {
    notes.push(
      "The approved link points to a local-only endpoint. This only works when both agents run on the same machine.",
    );
  } else if (targetReachability === "private") {
    notes.push(
      "The approved link points to a private-network endpoint. This only works when this agent can reach that LAN/VPN address.",
    );
  }

  if (params.requesterEndpoint && params.callbackConfirmed) {
    notes.push(
      "This contact is bidirectional: the peer confirmed it can ping this agent back, so both agents can initiate check, chat, and share.",
    );
  } else if (params.requesterEndpoint) {
    notes.push(
      "This contact is outbound-only for now: this agent sent a callback candidate, but the peer has not confirmed it can ping this agent back.",
    );
  } else {
    notes.push(
      "This contact is outbound-only from this side: this agent can call the peer, but the peer cannot call back unless this agent was started with a reachable address that city start can provide to contact.",
    );
  }
  return notes;
}
