/**
 * contact link approve 状态机。
 *
 * 关键点（中文）
 * - 远端 approve 只有一个入口：校验 link -> 保存 contact -> 消费 link。
 * - 同一个 agent 在 link 有效期内可重试，用于恢复“远端已保存、本地保存失败”的半建联。
 * - contact token 由协议自动交换，不依赖用户手动配置环境变量。
 */

import type { ContactApproveLinkResponse } from "@/types/contact/ContactLink.js";
import type {
  ApproveContactLinkRequestInput,
  ConfirmContactLinkRequestInput,
  ContactConfirmResponse,
} from "@/types/contact/ContactApproval.js";
import {
  createStableContactId,
  listContacts,
  normalizeContactEndpoint,
  readContact,
  saveContact,
} from "./ContactStore.js";
import {
  readContactLinkRecord,
  saveContactLinkRecord,
} from "./LinkStore.js";
import {
  createContactToken,
  hashContactToken,
} from "./Token.js";

export const CONTACT_LINK_NOT_FOUND_ERROR =
  "Contact link not found. This runtime does not have that link record. This usually means the approve request reached the wrong endpoint or port, the link was generated by another agent/project, or the local link store was cleared. If the code is expired, the remote agent returns Contact link expired instead.";

function failure(params: {
  ownerAgentName: string;
  endpoint: string;
  error: string;
}): ContactApproveLinkResponse {
  return {
    success: false,
    agentName: params.ownerAgentName,
    endpoint: params.endpoint,
    tokenForOwner: "",
    error: params.error,
  };
}

function confirmFailure(params: {
  ownerAgentName: string;
  error: string;
}): ContactConfirmResponse {
  return {
    success: false,
    agentName: params.ownerAgentName,
    confirmed: false,
    reachability: "inbound",
    error: params.error,
  };
}

function readCallbackCandidate(
  request: {
    callbackOffered?: boolean;
    endpoint?: string;
    tokenForRequester?: string;
  },
): {
  endpoint: string | null;
  token: string | null;
  error?: string;
} {
  if (request.callbackOffered !== true) {
    return {
      endpoint: null,
      token: null,
    };
  }
  const token = String(request.tokenForRequester || "").trim();
  if (!request.endpoint || !token) {
    return {
      endpoint: null,
      token: null,
      error: "Contact approve request is missing the peer callback token",
    };
  }
  try {
    return {
      endpoint: normalizeContactEndpoint(request.endpoint),
      token,
    };
  } catch {
    return {
      endpoint: null,
      token: null,
      error: "Contact approve request has an invalid peer callback endpoint",
    };
  }
}

async function findApprovedContact(params: {
  projectRoot: string;
  agentName: string;
}) {
  const stable = await readContact(
    params.projectRoot,
    createStableContactId(params.agentName),
  );
  if (stable) return stable;
  const contacts = await listContacts(params.projectRoot);
  const lower = params.agentName.trim().toLowerCase();
  return contacts.find((item) => item.name.toLowerCase() === lower) || null;
}

async function saveApprovedInboundContact(params: {
  projectRoot: string;
  agentName: string;
  tokenForOwner: string;
  nowMs: number;
}) {
  const existing = await findApprovedContact({
    projectRoot: params.projectRoot,
    agentName: params.agentName,
  });
  const hasOutboundSide = Boolean(existing?.endpoint && existing?.outboundToken);
  await saveContact(params.projectRoot, {
    id: existing?.id || createStableContactId(params.agentName),
    name: existing?.name || params.agentName,
    endpoint: existing?.endpoint || null,
    reachability: hasOutboundSide ? "bidirectional" : "inbound",
    status: "trusted",
    outboundToken: existing?.outboundToken || null,
    inboundTokenHash: hashContactToken(params.tokenForOwner),
    createdAt: existing?.createdAt || params.nowMs,
    lastSeenAt: params.nowMs,
  });
}

/**
 * 执行远端 link approve 状态转换。
 */
export async function approveContactLinkRequest(
  input: ApproveContactLinkRequestInput,
): Promise<ContactApproveLinkResponse> {
  const nowMs = input.nowMs ?? Date.now();
  const link = await readContactLinkRecord(input.projectRoot, input.request.linkId);
  if (!link) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: input.ownerEndpoint,
      error: CONTACT_LINK_NOT_FOUND_ERROR,
    });
  }
  if (link.expiresAt <= nowMs) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Contact link expired",
    });
  }
  if (hashContactToken(input.request.secret) !== link.secretHash) {
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Invalid contact link secret",
    });
  }
  const callbackCandidate = readCallbackCandidate(input.request);

  if (link.usedAt) {
    if (
      link.approvedAgentName === input.request.agentName &&
      link.tokenForOwner
    ) {
      let nextLink = link;
      if (
        !link.confirmedAt &&
        !callbackCandidate.error &&
        callbackCandidate.endpoint &&
        callbackCandidate.token
      ) {
        nextLink = {
          ...link,
          approvedEndpoint: callbackCandidate.endpoint,
          tokenForRequester: callbackCandidate.token,
          callbackReason: input.request.callbackReason || link.callbackReason || null,
        };
        await saveContactLinkRecord(input.projectRoot, nextLink);
      }
      await saveApprovedInboundContact({
        projectRoot: input.projectRoot,
        agentName: input.request.agentName,
        tokenForOwner: link.tokenForOwner,
        nowMs,
      });
      return {
        success: true,
        agentName: input.ownerAgentName,
        endpoint: link.endpoint,
        tokenForOwner: link.tokenForOwner,
      };
    }
    return failure({
      ownerAgentName: input.ownerAgentName,
      endpoint: link.endpoint,
      error: "Contact link already used",
    });
  }

  const tokenForOwner = createContactToken();
  const approvedLink = {
    ...link,
    usedAt: nowMs,
    approvedAgentName: input.request.agentName,
    approvedEndpoint: callbackCandidate.endpoint,
    tokenForOwner,
    tokenForRequester: callbackCandidate.token,
    callbackReason: callbackCandidate.error ? null : input.request.callbackReason || null,
  };

  // 先消费 link，再派生 contact；重试时以 link 记录为来源修复 contact，避免孤儿 trusted contact。
  await saveContactLinkRecord(input.projectRoot, approvedLink);
  await saveApprovedInboundContact({
    projectRoot: input.projectRoot,
    agentName: input.request.agentName,
    tokenForOwner,
    nowMs,
  });

  return {
    success: true,
    agentName: input.ownerAgentName,
    endpoint: link.endpoint,
    tokenForOwner,
  };
}

/**
 * 执行远端 confirm 状态转换。
 */
export async function confirmContactLinkRequest(
  input: ConfirmContactLinkRequestInput,
): Promise<ContactConfirmResponse> {
  const nowMs = input.nowMs ?? Date.now();
  const link = await readContactLinkRecord(input.projectRoot, input.request.linkId);
  if (!link) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: CONTACT_LINK_NOT_FOUND_ERROR,
    });
  }
  if (!link.usedAt && link.expiresAt <= nowMs) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact link expired",
    });
  }
  if (hashContactToken(input.request.secret) !== link.secretHash) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Invalid contact link secret",
    });
  }
  if (!link.usedAt || link.approvedAgentName !== input.request.agentName) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact link is not approved by this agent",
    });
  }

  let endpoint: string;
  try {
    endpoint = normalizeContactEndpoint(input.request.endpoint);
  } catch {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact confirm request has an invalid peer callback endpoint",
    });
  }
  const token = String(input.request.tokenForRequester || "").trim();
  if (!token) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact confirm request is missing the peer callback token",
    });
  }
  if (!link.tokenForRequester) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact link has no callback token to confirm",
    });
  }
  if (link.tokenForRequester !== token) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact confirm callback token does not match the approved token",
    });
  }
  if (!link.approvedEndpoint) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact link has no callback endpoint to confirm",
    });
  }
  if (normalizeContactEndpoint(link.approvedEndpoint) !== endpoint) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact confirm callback endpoint does not match the approved endpoint",
    });
  }
  const contact = await findApprovedContact({
    projectRoot: input.projectRoot,
    agentName: input.request.agentName,
  });
  if (!contact || contact.status !== "trusted") {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact not found for approved link",
    });
  }
  if (!link.tokenForOwner || contact.inboundTokenHash !== hashContactToken(link.tokenForOwner)) {
    return confirmFailure({
      ownerAgentName: input.ownerAgentName,
      error: "Contact token state does not match the approved link",
    });
  }

  if (
    contact.reachability === "bidirectional" &&
    contact.endpoint === endpoint &&
    contact.outboundToken === token
  ) {
    if (!link.confirmedAt) {
      // contact 已经完成双向升级时，重试 confirm 需要补齐 link 状态，避免最终状态分裂。
      await saveContactLinkRecord(input.projectRoot, {
        ...link,
        approvedEndpoint: endpoint,
        tokenForRequester: token,
        confirmedAt: nowMs,
      });
    }
    return {
      success: true,
      agentName: input.ownerAgentName,
      confirmed: true,
      reachability: "bidirectional",
    };
  }

  let callbackOk = false;
  try {
    callbackOk = await input.verifyCallback({ endpoint, token });
  } catch {
    callbackOk = false;
  }
  if (!callbackOk) {
    return {
      success: true,
      agentName: input.ownerAgentName,
      confirmed: false,
      reachability: "inbound",
      error: "Contact callback ping failed",
    };
  }

  await saveContact(input.projectRoot, {
    ...contact,
    endpoint,
    reachability: "bidirectional",
    outboundToken: token,
    inboundTokenHash: contact.inboundTokenHash,
    lastSeenAt: nowMs,
  });
  await saveContactLinkRecord(input.projectRoot, {
    ...link,
    approvedEndpoint: endpoint,
    tokenForRequester: token,
    confirmedAt: nowMs,
  });

  return {
    success: true,
    agentName: input.ownerAgentName,
    confirmed: true,
    reachability: "bidirectional",
  };
}
