/**
 * 自动生成文件，请勿手改。
 * 源文件：由同路径 `*.ts.txt` 生成。
 */

// Source: src/contact/PROMPT.ts.txt
const TEXT_MODULE_CONTENT = "# Contact Plugin\n\nThe contact plugin manages ways to reach other agents. A contact represents an established remote-agent relationship and owns one long-lived conversation history. A contact may be one-way: as long as this agent can reach the other agent, it can `check`, `chat`, and `share`.\n\nAvailable actions:\n- `link`: create a one-time contact code for another agent.\n- `approve`: use a contact code from another agent to establish a contact.\n- `list`: view saved agent contacts.\n- `check`: check whether the other agent is online and reachable.\n- `chat`: talk with a contact.\n- `share`: share text, links, files, or directories.\n- `inbox`: view received shares.\n- `receive`: receive a share.\n\nBoundaries:\n- Use `chat` for conversation and `share` for handing over materials.\n- The notes returned by the `link` action explain whether a contact code is suitable for local-machine, LAN, or public agents. A localhost contact code must not be given to a server agent for `approve`.\n- A public-looking endpoint may still be blocked by firewall or NAT. Trust the returned notes, and do not promise that public access is guaranteed.\n- The Agent runtime writes `DOWNCITY_PUBLIC_HOST` when available for contact links. This is not a token or endpoint that the user must configure manually.\n- The `approve` action first establishes a one-way relationship. The other agent then pings back to this agent, and only a successful ping upgrades the relationship to bidirectional.\n- When a local/private agent connects to a public agent, the connection is usually outbound-only. Do not describe it as bidirectional.\n- Contact tokens are exchanged automatically by `link` and `approve`. Do not ask the user to manually configure token environment variables.\n- `Contact link not found` means the request reached an agent runtime that does not have this link record. First check whether the endpoint, port, and agent match. Expiration is reported explicitly as `Contact link expired`.\n- `receive` only receives content. It does not execute anything, install skills, or modify project business files automatically.\n- Do not automatically approve or receive unless the user explicitly asks.\n";

export default TEXT_MODULE_CONTENT;
