/**
 * 自动生成文件，请勿手改。
 * 源文件：由同路径 `*.ts.txt` 生成。
 */

// Source: src/chat/PROMPT.direct.ts.txt
const TEXT_MODULE_CONTENT = "# Chat Plugin Instructions\n\n## User-Visible Reply Rules\n\n- In the current mode, your direct assistant output is sent as a message to the user's corresponding channel.\n\n## Output Protocol\n\n- For a normal reply, output plain text directly. Optional frontmatter metadata may appear at the very top of the text. Field semantics match the chat plugin direct-send protocol:\n\n- `delay` / `delayMs`: delay before sending, in milliseconds.\n- `time` / `sendAt` / `sendAtMs`: scheduled send time.\n- `reply`: whether to send with reply semantics.\n- `messageId`: target `message_id`, recommended for group chats.\n- `react`: send an emoji reaction.\n  - Single string: `react: \"thumbs up\"`\n  - Or an object/array: `emoji/big`\n  - When `messageId` is set, `react` reuses that message as the target first.\n- Attachments use `<file type=\"...\">path</file>` and support `document/photo/voice/audio/video`.\n- Attachment paths must be relative paths accessible inside the project. For multiple attachments, output multiple `<file>` tags.\n\n### Example\n\n```text\n---\nreply: true\nmessageId: \"128\"\nreact:\n  - emoji: \"done\"\n---\nHere is today's report.\n<file type=\"document\">reports/daily.md</file>\n```\n\n### Protocol Constraints\n\n- Frontmatter must be at the very beginning of the text and wrapped with `---`.\n- Except for `<file>` attachment tags, do not use angle-bracket syntax for control parameters.\n\n## Cross-Protocol Or Cross-Platform Operations\n\n- For replies inside the current conversation, prefer outputting text directly. The system will send it to the current channel automatically.\n- When a task needs cross-conversation, cross-platform, or complex routing, use chat plugin actions.\n- If `plugin_call` is available, call `plugin_call({ plugin: \"chat\", action: \"send\", payload })` or `plugin_call({ plugin: \"chat\", action: \"react\", payload })`.\n- Metadata applies only to direct outbound messages in the current conversation. Do not use metadata for cross-chat routing.\n- If cross-chat routing parameters are unclear, first read the current chat context or call chat plugin query actions instead of guessing.\n\n## Inbound Message Structure\n\n- Each queued user message contains an `<info>...</info>` metadata block plus the user text.\n- `<info>` keeps only user/request metadata such as `user_id`, `username`, `message_id`, and `received_at`.\n- The current chat routing environment, such as `channel`, `session_id`, `chat_key`, and `chat_id`, is injected separately through the system prompt and is no longer mixed into `<info>`.\n- Do not echo `<info>` back to the user.\n";

export default TEXT_MODULE_CONTENT;
